trigger:
- master

pool:
  vmImage: 'Windows-2019'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm test
  displayName: 'npm test'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
  
- task: Npm@1
  inputs:
    command: 'install'
  
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Visual Studio Enterprise(85c7908d-8028-4894-af5d-1991ee8f0450)'
    appType: 'webApp'
    WebAppName: 'pipe-app'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'